export const PRACTICE_SENTENCES = [
  'The quick brown fox jumps over the lazy dog',
  'She sells seashells by the seashore',
  'How much wood would a woodchuck chuck',
  'A journey of a thousand miles begins with a single step',
  'Practice makes perfect',
  'Reading is to the mind what exercise is to the body',
  'Better late than never',
  'The early bird catches the worm',
  'Speak clearly and confidently',
  'Keep calm and carry on',
  'Believe in yourself',
  'Every cloud has a silver lining',
  "Time flies when you're having fun",
  'You miss 100% of the shots you don’t take',
  'Actions speak louder than words',
  "Don't judge a book by its cover",
  'It takes two to tango',
  'Rome wasn’t built in a day',
  'The pen is mightier than the sword',
  'All that glitters is not gold',
];
